### PR TITLE
Fix repeat sequence double running bug

### PR DESCRIPTION
**Pull request by kaphula**
There's a bug in repeat sequence behavior where if its sequence list's first behavior returns `Running`, then when the behavior tree is ticked again, the condition behavior of repeat sequence is run again even though it should not be allowed when the behavior tree is in the middle of executing its sequence.

This PR fixes that, adds some tests and additional documentation.

### CODE REVIEW

**Comment by kaphula** [comment]
Actually I want to investigate and test this a bit more since it fixes some parts from my own application but break others.

**Comment by kaphula** [comment]
I think I got it now but let's keep it in draft for few days just to be safe. I get some time to see it in action and catch any funky behavior in case there's still something that is broken.

**Comment by kaphula** [comment]
I have not noticed anything weird and my code is now behaving as expected with this PR.

**Comment by Sollimann** [comment]
Will find some time in the next couple of days to review it👌

**Review by kembofly — APPROVED** [review]
Great job with the thorough investigation and testing!

**Comment by Sollimann** [comment]
@kaphula Wrt to the Fallback node. My preference is to keep the number of behaviors to a minimum unless they are strictly needed, and cannot be constructed with the existing behaviors already. The typical `Fallback` node corresponds to the `Select` behavior already.

```rust
/// Runs behaviors one by one until a behavior succeeds.
///
/// If a behavior fails it will try the next one.
/// Fails if the last behavior fails.
/// Can be thought of as a short-circuited logical OR gate.
Select(Vec<Behavior<A>>),
```

This behavior iterates over its children, executing them one at a time. If a child behavior results in a Failure, it moves on to the next child. The `Select` behavior succeeds as soon as one of its children succeeds. If all the children fail, then the Select behavior itself fails, exactly as a Fallback node would.

you can compare with Fallback node in the defacto c++ lib for behavior trees: https://www.behaviortree.dev/docs/nodes-library/fallbacknode/

**Comment by kaphula** [comment]
> @kaphula Wrt to the Fallback node. My preference is to keep the number of behaviors to a minimum unless they are strictly needed, and cannot be constructed with the existing behaviors already. The typical `Fallback` node corresponds to the `Select` behavior already.

I agree with the reasoning of don't bloat for the sake of it. I am currently using this kind of extension to emulate the fallback behavior which works just fine for me:

```rust
pub fn fallback_bonsai_behavior<A: Clone>(from: Box<Behavior<A>>, to: Box<Behavior<A>>) -> Behavior<A> {
    If(from, to.clone(), to)
}
```
But now that I think of it, `Select` probably does serve the exact same purpose as fallback if you just declare the last behavior of `Select` as your fallback behavior. Thanks!

**Pull request merged**
